name: Run Node Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm install axios moment fs.promises

      - name: node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_KEYWORDS: ${{ secrets.KEY }}
        run: node 1.js

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: tgiy/dc
          branch: main
          directory: ./logs
