name: Run Node Script
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_scraper]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ac repo
        uses: actions/checkout@v6
        with:
          repository: tgiy/ac
          ref: main
          token: ${{ secrets.CD }}
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install axios moment fs.promises
      - name: Run script
        env:
          GT10: ${{ secrets.GT10 }}
          GT9: ${{ secrets.GT9 }}
          GT8: ${{ secrets.GT8 }}
          GT7: ${{ secrets.GT7 }}
          GT6: ${{ secrets.GT6 }}
          GT5: ${{ secrets.GT5 }}
          GT4: ${{ secrets.GT4 }}
          GT3: ${{ secrets.GT3 }}
          GT2: ${{ secrets.GT2 }}
          GT: ${{ secrets.GT }}
          KEY: ${{ secrets.KEY }}
        run: node 1.js
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          repository: tgiy/dc
          ref: main
          path: dc
          token: ${{ secrets.CD }}
      - name: Copy s.json to dc
        run: |
          mkdir -p dc/logs
          cp /tmp/s.json dc/logs/s.json
      - name: Check for changes
        id: check_changes
        run: |
          cd dc
          content=$(cat logs/s.json | tr -d '[:space:]')
          if [ "$content" = "[]" ]; then
              echo "changes=false" >> $GITHUB_OUTPUT
          else
              git add .
              modified=$(git status --porcelain)
              if [ -n "$modified" ]; then
                  echo "changes=true" >> $GITHUB_OUTPUT
              else
                  echo "changes=false" >> $GITHUB_OUTPUT
              fi
          fi
      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cd dc
          git config --global user.name 'tgiy'
          git config --global user.email 'tgiy@action.com'
          git commit -m "Update s.json"
          git remote set-url origin https://tgiy:${{ secrets.CD }}@github.com/tgiy/dc.git
          git pull --rebase origin main
          git push origin main
