name: Run Node Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm install axios moment fs.promises

      - name: node
        env:
          GT: ${{ secrets.GT }}
          KEY: ${{ secrets.KEY }}
        run: node 1.js
        
      - name: Create
        run: mkdir -p ./logs

      - name: Copy
        run: cp /tmp/s.json ./logs/s.json

      - name: Push to private repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          token: ${{ secrets.CD }}
          repository: tgiy/dc
          branch: main
          directory: ./logs
