name: Run Node Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm install axios moment fs.promises

      - name: node
        env:
          GT: ${{ secrets.GT }}
          KEY: ${{ secrets.KEY }}
        run: node 1.js
        
      - name: Create
        run: mkdir -p ./logs



      - name: Checkout public repo job6
        uses: actions/checkout@v4
        with:
          repository: tgiy/dc
          ref: main
          path: dc
          token: ${{ secrets.CD }} 
      - name: Copy
        run: |
          cd ac
          shopt -s extglob
          rsync -rv ../dc/
      - name: Check if changes were made job6
        id: check_changes
        run: |
          cd dc
          modified=$(git status --porcelain)
          if [ -n "$modified" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cd dc
          git config --global user.name 'zz'
          git config --global user.email 'zz@gmail.com'
          git add ac
          git commit -m "zz"
          git remote set-url origin https://tgiy:${{ secrets.CD }}@github.com/tgiy/dc.git
          git pull --rebase origin main
          git push origin main

